version: "3.9"
services:
  server:
    build: ./server
    ports:
      - "8000:8000"
    depends_on:
      - database
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
  database:
    build: ./database
    ports:
      - "27018:27017"
